# Generated by Django 5.0.4 on 2024-04-18 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Especialidade')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icones', verbose_name='Ícone')),
            ],
            options={
                'verbose_name': 'Speciality',
                'verbose_name_plural': 'Specialities',
            },
        ),
        migrations.CreateModel(
            name='MedicalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('profile_pic', models.ImageField(upload_to='profile_pic', verbose_name='Foto de Perfil')),
                ('street', models.CharField(max_length=100, verbose_name='Rua')),
                ('district', models.CharField(max_length=100, verbose_name='Bairro')),
                ('number', models.IntegerField(verbose_name='Número')),
                ('crm', models.CharField(max_length=30, verbose_name='CRM')),
                ('cep', models.CharField(max_length=15, verbose_name='CEP')),
                ('rg', models.ImageField(upload_to='rg', verbose_name='RG')),
                ('cim', models.ImageField(upload_to='cim', verbose_name='Cedula Identidade Médica')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('consult_price', models.FloatField(default=100, verbose_name='Valor da Consulta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('speciality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.speciality', verbose_name='Especialidade')),
            ],
            options={
                'verbose_name': 'Medical Data',
                'verbose_name_plural': 'Medical Data',
            },
        ),
    ]
