# Generated by Django 5.0.4 on 2024-04-19 04:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Especialidade')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icones', verbose_name='Ícone')),
            ],
            options={
                'verbose_name': 'Speciality',
                'verbose_name_plural': 'Specialities',
            },
        ),
        migrations.CreateModel(
            name='MedicalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('masc', 'Masculino'), ('fem', 'Feminino'), ('nb', 'Não Binário'), ('none', 'Prefiro não informar')], default='none', max_length=10, verbose_name='Gênero')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('profile_pic', models.ImageField(upload_to='profile_pic/', verbose_name='Foto de Perfil')),
                ('street', models.CharField(max_length=100, verbose_name='Rua')),
                ('district', models.CharField(max_length=100, verbose_name='Bairro')),
                ('number', models.IntegerField(verbose_name='Número')),
                ('crm', models.CharField(max_length=30, verbose_name='CRM')),
                ('cep', models.CharField(max_length=15, verbose_name='CEP')),
                ('rg', models.ImageField(upload_to='rg/', verbose_name='RG')),
                ('cim', models.ImageField(upload_to='cim/', verbose_name='Cedula Identidade Médica')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('consult_price', models.DecimalField(decimal_places=2, default=100, max_digits=10, verbose_name='Valor da Consulta')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('speciality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.speciality', verbose_name='Especialidade')),
            ],
            options={
                'verbose_name': 'Medical Data',
                'verbose_name_plural': 'Medical Data',
            },
        ),
        migrations.CreateModel(
            name='OpenDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data e Horário')),
                ('status', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.medicaldata')),
            ],
            options={
                'verbose_name': 'Open Dates',
                'verbose_name_plural': 'Open Dates',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Agendada'), ('F', 'Finalizada'), ('C', 'Cancelada'), ('I', 'Iniciada')], default='A', max_length=1)),
                ('link', models.URLField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('open_date', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.opendates')),
            ],
        ),
    ]
